// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const effectiveUrl = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY ? SUPABASE_URL : "https://localhost.invalid";
const effectiveKey = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY ? SUPABASE_PUBLISHABLE_KEY : "public-anon-key";

export const supabase = createClient<Database>(effectiveUrl, effectiveKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});